### ISSUE TITLE
Move the Ping Drive command here

### ISSUE THREAD

**Issue by Finesse** [forikal-uk/xml-authoring-tools#3]
I develop the Ping Drive command for the tools in [a separate repository](https://github.com/forikal-uk/ping-drive). I noticed that there is some common code in the repositories, e.g. [here](https://github.com/forikal-uk/xml-authoring-tools/blob/feature-helloworld/src/Command/AbstractCommand.php#L65), [there](https://github.com/forikal-uk/ping-drive/blob/master/src/Commands/PingDriveCommand.php#L419).

So why not to keep the Ping Drive command in this repository to reuse the code and make the system simpler?

**Comment by forikal-uk** [comment]
Yes. I noticed that there is some common code and I think it would be good to resuse if possible.

I'd prefer to keep these project in isolation as much as possible and use techniques to reuse code.

One idea might be to extract the "configuration finder" into its own package and make all projects use it.

I also thought that making use of an abstract command class might be good. So, all commands in the suites extend a particular abstract class which holds common code.

I was going to apply refactoring after the first set of commands are built. But now we have some code, I see the need.

In the first instance I will create a "library project" and give every one access to it.

Then, any code which becomes common can be moved into that project and reused by other projects.

This will allow code reuse plus loose coupling of the components at the same time.

**Comment by Finesse** [comment]
A common repository is a good solution too. Thank you.

I will move my mockable Google API abstraction there. And I think that it would be great if Igor moves AbstractCommand there too.

**Comment by forikal-uk** [comment]
Just to keep a log of what is being moved: 

- @Finesse Finesse moved the Google API helper and the console logger from [ping-drive](https://github.com/forikal-uk/ping-drive) to the [library](https://github.com/forikal-uk/xml-authoring-library)
- @forikal-uk Moved a snippet of docs How to Set up Google Api from [gsheet-to-xml](https://github.com/forikal-uk/gsheet-to-xml) to the [library](https://github.com/forikal-uk/xml-authoring-library)

**Comment by forikal-uk** [comment]
I guess if we do refactorings we could add a line to the commit message and it will [autolink update](https://help.github.com/articles/autolinked-references-and-urls/) this Issue with a log:

`See https://github.com/forikal-uk/xml-authoring-tools/issues/3`

That might be too much to remember but, any way, just a thought.
