### ISSUE TITLE
Test on Windows 10 bash CLI 

### ISSUE THREAD

**Issue by igormukhingmailcom** [forikal-uk/xml-authoring-tools#4]
This project was tested on Mac. So it will work on Linux as well.

For Windows 10 bash CLI - it also should work, but I have no chance to test as far as I haven’t computer with Windows 10.

Could anyone test, please?

**Comment by Finesse** [comment]
What about using [AppVeyor](http://appveyor.com) to test the code on Windows and Linux automatically? Here is an example of using AppVeyor to test a PHP code on Windows: https://blog.wyrihaximus.net/2016/11/running-php-unit-tests-on-windows-using-appveyor-and-chocolatey/

**Comment by forikal-uk** [comment]
Thanks @igormukhingmailcom for this raising this issue.

I have a PC, so I will test it on it later today.

Thanks also so @Finesse. [AppVeyor](http://appveyor.com/) looks really interesting. I shall have to add it to the list of things I need to learn about.

**Comment by forikal-uk** [comment]
Hi, it is taking time for me to get around to test this on Windows. Sorry. 

I will test it on Mac first now then go onto Windows after that.

**Comment by forikal-uk** [comment]
I have put the xml-authoring-project on Windows 10 and ran hello-world command from that context.

It worked OK.

https://github.com/forikal-uk/xml-authoring-project/issues/3#issuecomment-394233058
