### ISSUE TITLE
Notes as I experience the code first time.

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/xml-authoring-tools#5]
## Goal

Write notes as I experience running this tool for the first time.

## Why

If I write notes as I run the code for the first time

we get:

- New user's perspective on the project 
- Feedback to the developer to see how his code is seen
- List of comments, within a narrative context, that can be referred to in bugs or enhancements.
- Potential information to add to the documentation.

## How

* Follow the docs and write notes below.
* Take screen grabs in case they might be handy for docs.

**Comment by forikal-uk** [comment]
## First impressions

Looking at the [feature branch](https://github.com/forikal-uk/xml-authoring-tools/tree/feature-helloworld)  I am wondering how to go about testing this.

The context for these tools is the [xml-authoring-project](https://github.com/forikal-uk/xml-authoring-project) and a lot of the code is in the [xml-authoring-library](https://github.com/forikal-uk/xml-authoring-library).

----

## Plan 

I will test the the [xml-authoring-project](https://github.com/forikal-uk/xml-authoring-project)  first, because that is the high end usage. 

Then I will go down to the libary and follow the [contribution](https://github.com/forikal-uk/xml-authoring-library#contribution) steps to make tests.

Then, I will try hello world in standalone context.

**Comment by igormukhingmailcom** [comment]
@forikal-uk , please ignore that feature branch as far as it no more actual. It was merged to master long time ago and should be removed.

**Comment by igormukhingmailcom** [comment]
Removed:

```
git push -d origin feature-helloworld
To github.com:forikal-uk/xml-authoring-tools.git
 - [deleted]         feature-helloworld
```

**Comment by forikal-uk** [comment]
Thanks.
